cython_modules:
  - name: fletplus.router.router_cy
    path: fletplus/router/router_cy.pyx
  - name: fletplus.http.disk_cache
    path: fletplus/http/disk_cache.pyx
  - name: fletplus.state.state
    path: fletplus/state/state.pyx
  - name: fletplus.utils.responsive_manager
    path: fletplus/utils/responsive_manager.pyx
