[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fletplus"
version = "0.2.3"
description = "Componentes visuales avanzados para Flet en Python"
authors = [
  { name="Adolfo GonzÃ¡lez", email="adolfogonzal@gmail.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
  "flet>=0.27.0"
]

[project.scripts]
fletplus-demo = "fletplus_demo.app:run"
fletplus_demo = "fletplus_demo.app:run"

[project.urls]
Homepage = "https://github.com/Alphonsus411/fletplus"
Repository = "https://github.com/Alphonsus411/fletplus"
Documentation = "https://github.com/Alphonsus411/fletplus#readme"
